(() => {
  const mic = document.getElementById('mic');
  const core = document.getElementById('core');
  const stateEl = document.getElementById('state');
  const subEl = document.getElementById('sub');
  if (!mic) return;
  const cleanMic = mic.cloneNode(true);
  mic.replaceWith(cleanMic);
  let ws = null, stream = null, audioContext = null, inputContext = null;
  let processor = null, source = null, gain = null, listening = false;
  let nextPlayTime = 0, lastUserSpeech = false, reconnectTimer = null;
  const report=(voice,message='')=>fetch('/api/voice-state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({voice,message})}).catch(()=>{});
  function setState(value,subtitle){const v=String(value||'idle').toLowerCase();if(core)core.dataset.state=v;if(stateEl)stateEl.textContent=value?String(value).toUpperCase():'IDLE';if(subEl&&subtitle)subEl.textContent=subtitle;report(v,subtitle||'')}
  function bytesToBase64(bytes){let s='';for(let i=0;i<bytes.length;i+=0x8000)s+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(s)}
  function base64ToBytes(t){const b=atob(t),o=new Uint8Array(b.length);for(let i=0;i<b.length;i++)o[i]=b.charCodeAt(i);return o}
  function pcm16(f,rate){if(rate===16000){const o=new Int16Array(f.length);for(let i=0;i<f.length;i++){const s=Math.max(-1,Math.min(1,f[i]));o[i]=s<0?s*32768:s*32767}return o}const ratio=rate/16000,n=Math.max(1,Math.round(f.length/ratio)),o=new Int16Array(n);let off=0;for(let i=0;i<n;i++){const end=Math.min(f.length,Math.round((i+1)*ratio));let sum=0,c=0;while(off<end){sum+=f[off++];c++}const s=Math.max(-1,Math.min(1,c?sum/c:0));o[i]=s<0?s*32768:s*32767}return o}
  function playPCM16(b64,rate=24000){const bytes=base64ToBytes(b64),samples=new Int16Array(bytes.buffer,bytes.byteOffset,Math.floor(bytes.byteLength/2));if(!audioContext)audioContext=new AudioContext({sampleRate:rate});if(audioContext.state==='suspended')audioContext.resume().catch(()=>{});const buf=audioContext.createBuffer(1,samples.length,rate),ch=buf.getChannelData(0);for(let i=0;i<samples.length;i++)ch[i]=samples[i]/32768;const node=audioContext.createBufferSource();node.buffer=buf;node.connect(audioContext.destination);const start=Math.max(audioContext.currentTime+.02,nextPlayTime);node.start(start);nextPlayTime=start+buf.duration}
  async function stopVoice(send=true){listening=false;if(send&&ws?.readyState===1)try{ws.send(JSON.stringify({type:'stop'}))}catch(_){}for(const x of [processor,source,gain])try{x?.disconnect()}catch(_){}processor=source=gain=null;try{await inputContext?.close()}catch(_){}inputContext=null;stream?.getTracks().forEach(t=>t.stop());stream=null;try{ws?.close()}catch(_){}ws=null;cleanMic.textContent='♩';cleanMic.title='Voice input';setState('Idle','Press Ctrl once to wake JARVIS.')}
  async function startVoice(){if(listening)return;try{stream=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true,autoGainControl:true}});const protocol=location.protocol==='https:'?'wss':'ws';ws=new WebSocket(`${protocol}://${location.host}/api/live`);ws.binaryType='arraybuffer';await new Promise((res,rej)=>{const timer=setTimeout(()=>rej(new Error('Voice connection timed out.')),10000);ws.addEventListener('open',()=>{clearTimeout(timer);res()},{once:true});ws.addEventListener('error',()=>{clearTimeout(timer);rej(new Error('Could not connect to Gemini Live.'))},{once:true})});listening=true;cleanMic.textContent='■';cleanMic.title='Stop voice conversation';setState('Listening',"I'm listening — speak naturally in Arabic or English.");ws.onmessage=e=>{let m;try{m=JSON.parse(e.data)}catch(_){return}if(m.type==='ready')setState('Listening',`Voice online — ${m.voice||'Charon'} · عربي / English`);else if(m.type==='audio'){setState('Speaking','JARVIS is speaking…');playPCM16(m.data,Number(m.sample_rate)||24000)}else if(m.type==='transcript'){if(m.role==='user'&&stateEl)stateEl.textContent='LISTENING';if(m.role==='assistant'&&subEl)subEl.textContent=m.text}else if(m.type==='state')setState(m.value,m.value==='speaking'?'JARVIS is speaking…':"I'm listening…");else if(m.type==='error'){setState('Error',m.message||'Voice connection failed.');stopVoice(false).catch(()=>{})}};ws.onclose=()=>{if(!listening)return;stopVoice(false).catch(()=>{});if(!reconnectTimer)reconnectTimer=setTimeout(()=>{reconnectTimer=null;startVoice().catch(()=>{})},1200)};inputContext=new AudioContext();if(inputContext.state==='suspended')await inputContext.resume();source=inputContext.createMediaStreamSource(stream);processor=inputContext.createScriptProcessor(4096,1,1);gain=inputContext.createGain();gain.gain.value=0;source.connect(processor);processor.connect(gain);gain.connect(inputContext.destination);processor.onaudioprocess=e=>{if(!listening||ws?.readyState!==1)return;const input=e.inputBuffer.getChannelData(0);let sum=0;for(let i=0;i<input.length;i++)sum+=input[i]*input[i];const rms=Math.sqrt(sum/input.length),talking=rms>0.02;if(talking!==lastUserSpeech){lastUserSpeech=talking;report(talking?'user_speaking':'listening',talking?'User is speaking':"I'm listening")}const pcm=pcm16(input,inputContext.sampleRate);try{ws.send(JSON.stringify({type:'audio',data:bytesToBase64(new Uint8Array(pcm.buffer,pcm.byteOffset,pcm.byteLength))}))}catch(_){}}}catch(err){await stopVoice(false);setState('Error',err?.message||'Microphone unavailable.')}}
  window.JARVIS_WAKE=async()=>{if(listening){await stopVoice();return}await startVoice()};
  cleanMic.addEventListener('click',()=>window.JARVIS_WAKE());
  window.addEventListener('load',()=>setTimeout(()=>startVoice().catch(()=>{}),900));
})();